name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Node.js (for Capacitor)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3️⃣ Install npm dependencies
    - name: Install dependencies
      run: npm install

    # 4️⃣ Setup JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # 5️⃣ Add & Sync Capacitor Android platform
    - name: Add & Sync Capacitor Android
      run: |
        npx cap add android || echo "Android platform already exists"
        npx cap sync android

    # 6️⃣ Update app icon & app name BEFORE build
    - name: Set app name & icon
      run: |
        if [ -f ./gg.png ]; then
          cp gg.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          cp gg.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp gg.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp gg.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp gg.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        fi
        sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">Fakebook<\/string>/' android/app/src/main/res/values/strings.xml

    # 7️⃣ Grant gradlew permission
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 8️⃣ Build APK
    - name: Build Android APK
      run: ./gradlew assembleDebug

    # 9️⃣ Upload APK as artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Fakebook-debug
        path: android/app/build/outputs/apk/debug/*.apk
